middleware:
  middlewares:
    - class: "middlewares.AuthorizationMiddleware"
      token: "12345"

retry:
  wait_time: 0
  max_attempts: 3

worker:
  workers:
    - class: "workers.AkashWorker"
      name: "akash-web"
      priority: 100
      models:
        - "deepseek-reasoner"
        - "AkashGen"
      aliases:
        deepseek-reasoner: "DeepSeek-V3.1"

    - class: "workers.PollinationsWorker"
      name: "pollinations"
      priority: 100
      models:
        - "deepseek-reasoner"
        - "qwen-coder"
        - "openai-reasoning"
      api_key: ""
      aliases:
        deepseek-reasoner: "deepseek-reasoning"
        gemini-2.5-flash-lite: "gemini"
        gpt-5-nano: "openai"
        gpt-4o-mini-audio-preview: "openai-audio"
        o4-mini: "openai-reasoning"
    
    - class: "workers.LongchatWorker"
      name: "longchat"
      priority: 100
      models:
        - "longcat-flash"
        - "longcat-flash-search"
      api_key: ""
    
    - class: "workers.ZaiWorker"
      name: "z.ai"
      priority: 100
      models:
        - "GLM-4.5"
        - "GLM-4.5-Air"
        - "GLM-4.5v"
      api_key: ""
    
    - class: "workers.K2ThinkWorker"
      name: "k2think"
      priority: 100
      models:
        - "K2-Think"
    
    - class: "workers.ChatbotWorker"
      name: "chatbot"
      priority: 150
      models:
        - "grok-4-fast"
        - "grok-4-fast-reasoning"
      aliases:
        grok-4-fast: "chat-model"
        grok-4-fast-reasoning: "chat-model-reasoning"
    
    - class: "workers.OpenAiWorker"
      name: "chatbot-starter"
      models:
        - "deepseek-chat"
        - "deepseek-reasoner"
      priority: 100
      api_key: ""
      models_url: ""
      completions_url: "https://ai-chatbot-starter.edgeone.app/api/ai"
      fake_streaming_interval: 10

proxy:
  local:
    class: "proxies.ProxyManager"
    url: ""
    initial:
      - "socks5://127.0.0.1:1080"
    timeout: 9
    max_retries: 3
    repeat: 1

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    fastapi_style:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

    default_style:
      format: "%(levelname)s:    %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default_style
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: WARNING
      formatter: fastapi_style
      filename: ../logs/app.log
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf-8

  root:
    level: DEBUG
    handlers: [console, file]

  loggers:
    uvicorn:
      level: INFO
      handlers: [console]
      propagate: false

    blacksheep:
      level: INFO
      handlers: [console]
      propagate: false
